name: Build and Push
uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ghcr.io/vonkristoff/api-cooltrees-gallery/api:latest
